import Link from "next/link";
const sources=[
 {title:'GST Acts · CBIC',url:'https://cbic-gst.gov.in/gst-acts.html',note:'CGST, IGST, UTGST and constitutional framework. Follow the current legal text and amendment instruments.'},
 {title:'Tax Information Portal · CBIC',url:'https://taxinformation.cbic.gov.in/',note:'Acts, rules, rate notifications, circulars and instructions. Establish the instrument and its effective date for your case.'},
 {title:'GST portal & operational advisories',url:'https://www.gst.gov.in/',note:'Filing facilities, advisory updates and taxpayer operations. Check period-specific due dates and extensions.'},
 {title:'GSTR-1A · official user guide',url:'https://tutorial.gst.gov.in/userguide/returns/GSTR_1.htm',note:'Optional same-period correction timing and the subsequent recipient GSTR-2B process.'},
 {title:'GSTR-2B · official user guide',url:'https://tutorial.gst.gov.in/userguide/returns/FAQ_gstr2b.htm',note:'Statement data and its limits. Portal matching does not replace legal ITC eligibility.'},
 {title:'E-invoice guidance · official IRP',url:'https://einvoice6.gst.gov.in/content/faq-powered-by-irisirp/',note:'IRN operations, including the AATO ₹10 crore-plus 30-day reporting restriction described from April 2025.'},
 {title:'2025 rate-transition FAQ · GST Council',url:'https://gstcouncil.gov.in/sites/default/files/2025-09/faq.pdf',note:'Background to the September 2025 transition. Use the implemented rate notifications for actual commodity or service decisions.'},
 {title:'2026 GST amendment notes · Ministry of Finance',url:'https://www.indiabudget.gov.in/doc/cen/dojstru1.pdf',note:'Explains the proposed discount, refund and intermediary-service changes and distinguishes commencement requirements. Budget explanations alone do not establish enacted, commenced law.'},
];
export default function Resources(){return <main className="resource-wrap"><Link href="/">← All modules</Link><p className="eyebrow" style={{marginTop:24}}>SOURCE DESK</p><h1>Keep the law beside the lesson.</h1><p>This is a static educational course. It does not refresh rates, filing dates or amendment status automatically. The initial research was completed on 7 October 2026; selected official sources and their scope are recorded below.</p><article><h3>How to use the exercises</h3><p>Each rate and calculation base is an express assumption. The examples teach the method; they do not identify the current GST rate for a commodity or certify a live filing position. Check the transaction date, classification, State, notification and exceptions before applying the method to a real case.</p></article><article><h3>Amendment checkpoints</h3><ul><li><strong>ISD:</strong> lessons use the amended mandatory framework from 1 April 2025 for covered input-service invoices. <a href="https://taxinformation.cbic.gov.in/content-page/explore-act/1000289/1000001" target="_blank" rel="noreferrer">Read section 20 ↗</a></li><li><strong>Construction ITC:</strong> the lessons flag the amended “plant and machinery” wording and explanations. <a href="https://taxinformation.cbic.gov.in/content-page/explore-act/1000286/1000001" target="_blank" rel="noreferrer">Read section 17 ↗</a></li><li><strong>Demands:</strong> section 74A is distinguished for FY 2024–25 onward; earlier periods retain their section 73/74 analysis.</li><li><strong>2026 discounts:</strong> the official section source snapshot labels the change as awaiting notified commencement. Discount exercises expressly use the pre-amendment conditions. Check later Gazette notifications before deciding the applicable version. <a href="https://taxinformation.cbic.gov.in/content-page/explore-act/1000284/1000001" target="_blank" rel="noreferrer">Read section 15 ↗</a></li><li><strong>Cross-border intermediary services and refunds:</strong> 2026 changes require an express commencement check; the course avoids an unconditional rate or refund conclusion for those transitions.</li></ul></article><h2>Official reading</h2>{sources.map(source=><article key={source.url}><h3><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></h3><p style={{marginBottom:0,color:'var(--text-dim)'}}>{source.note}</p></article>)}<article><h3>Your learning data</h3><p>Chapter completion and completed quiz scores are stored in this browser under a GST-specific key. They do not sync across devices. Clearing browser storage removes the records. Unfinished quiz attempts are not saved.</p></article></main>}
